---
title: Madi Cranmer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: www.madi-designs.com
baseurl: "/madi-designs"
email: madison_cranmer@hotmail.com
description: 'Madison Cranmer''s portflio website that will showcase all of her work. '
people:
- name: Madison Cranmer
  pic: 1
  position: Design Student
  social:
  - title: twitter
    url: 
  - title: facebook
    url: 
social:
- title: github
  url: https://github.com/mcranmer1
- title: linkedin
  url: https://www.linkedin.com/in/madison-cranmer-982b41135/
- title: facebook
  url: https://www.facebook.com/madi.cranmer
markdown: kramdown
permalink: pretty
