---
title: Awesome Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://y7kim.github.io
baseurl: "/madi-designs.com"
email: madison_cranmer@hotmail.com
description: This is Madison Cranmers portfolio website.  
social:
- title: github
  url: https://github.com/mcranmer1
- title: linkedin
  url: https://www.linkedin.com/in/madison-cranmer-982b41135/
- title: facebook
  url: https://www.facebook.com/madi.cranmer
markdown: kramdown
permalink: pretty
